import matplotlib
import matplotlib.pyplot as plt
import matplotlib.colors
import numpy as np
import os

labels = {0:"theta",
          1:"azmiuth",
          2:"nPE",
          3:"nHits"}

# plot the features extracted from gamma dataset
def plot_ground_truth():
    samples = np.load("gamma_data.npy")
    # normalization values (mean and std)
    samples -= [4.32868898e-01, -1.03701055e-02, 2.64389896e+00, 1.58296906e+02]
    samples /= [0.294857, 1.7961102, 0.5629358, 178.98788]
    plot_4(samples)

# plot the distribution of features generated by the generator
def plot_4(samples, show=False, save=None):
    plt.figure(figsize=(16, 16))
    for i in range(4):
        plt.subplot(2, 2, i + 1)
        plt.hist(samples[:, i], bins=50)
        plt.title(labels[i])
    if show: plt.show()
    if save is not None:
        plt.savefig(save)

# plot distribution of pixel values in 40x40 mapped image
def plot_hists(grid):
    plt.figure(figsize=(16,16))
    plt.title('distribution of values per dimension')
    for i in range(grid.shape[3]):
        plt.hist(grid[:,:,:,i].flatten(), bins=50, alpha=0.5, label='dim %i' % i)
    plt.legend()
    plt.show()

#
# plot a variety of visualizations from pixelcnn 40x40 image output
# if 1 dim: raw 40x40 grid, grid of pmts, single pmts
# if 2 dim: 40x40 grid side by side, grid of pmts side by side
#
def plot_tanks_from_grid(path="./HAWC/", sub="saves/", num=2, dim=1):
    prefix = "2" if dim==2 else ""
    grid = os.path.join(path, sub, "hawc" + prefix +"_sample"+str(num)+".npz")
    grid = np.load(grid)['arr_0']
    plot_40x40(grid, 'pixelcnn pmt hits - 40x40 grid, log(charge)')
    plot_pmts(grid, 'pixelcnn pmt hits - log(charge)')
    for i in range(5, 16):
        plot_pmts(grid, 'pixelcnn pmt hits - log(charge) - single', single=i)

# plot a simple grid of 40x40 images
def plot_40x40(grid, title):
    fig = plt.figure(figsize=(20, 20))
    for i in range(16):
        plt.subplot(4, 4, i + 1)
        if grid.shape[3] == 1:
            plt.imshow(grid[i][:, :, 0])
        elif grid.shape[3] == 2:
            plt.title('event %i, dim %i' % (i // 2, i % 2))
            if i % 2 == 1:
                grid[i // 2][:, :, i % 2] = np.clip(grid[i//2][:,:,i%2], 50, 150)
            plt.imshow(grid[i // 2][:, :, i % 2])
        plt.colorbar()
    fig.suptitle(title)
    plt.show()

# plot a scatterplot from 40x40 mapped images corresponding to real locations of pmts
# plot a 2 by 2 plot, or a single plot if single=True
# does some additional data cleaning if data is not sparse
def plot_pmts(grid, title, single=None, sparse=False):
    layout = np.load("data/layout.npy")
    from squaremapping import sqmap
    inv_sqmap = dict((v, k) for (k, v) in sqmap.iteritems())
    good_cords = layout[:, 0] != 0.0
    x_cord = layout[:, 0]
    y_cord = layout[:, 1]
    if not single:
        fig = plt.figure(figsize=(16, 16))
        fig.suptitle(title)
        for i in range(4):
            A = np.zeros((1200, 1))
            for x, y in inv_sqmap.keys():
                pmt_num = inv_sqmap[(x, y)]
                if grid.shape[3] == 1:
                    A[pmt_num - 1] = grid[i][x, y, 0]
                elif grid.shape[3] == 2:
                    A[pmt_num - 1] = grid[i // 2][x, y, i % 2]
            if not sparse:
                # remove values of 0 for a cleaner plot
                good_cords = np.minimum(A[:, 0] != 0, good_cords)
            A += 1
            plt.subplot(2, 2, i + 1)
            plt.scatter(x_cord[good_cords], y_cord[good_cords], s=50, c=A[:, 0][good_cords] + 0.1, marker='o',
                        linewidths=0.01, alpha=0.7, norm=matplotlib.colors.LogNorm())
            plt.colorbar()
        plt.show()
    else:
        i = single
        fig = plt.figure(figsize=(16, 16))
        plt.title('pixelcnn pmt hits - log(charge) - single')
        A = np.zeros((1200, 1))
        for x, y in inv_sqmap.keys():
            pmt_num = inv_sqmap[(x, y)]
            A[pmt_num - 1] = grid[i][x, y, 0] + 1

        plt.scatter(x_cord[good_cords], y_cord[good_cords], s=50, c=A[:, 0][good_cords] + 0.1, marker='o',
                    linewidths=0.01, alpha=0.7, norm=matplotlib.colors.LogNorm())
        plt.colorbar()
        plt.show()

if __name__ == "__main__":
    import sys
    plot_tanks_from_grid(num=sys.argv[1], dim=2)
